//
// Created by ziv on 15/02/17.
//

#ifndef ARDUINOEXAMPLE_ARDUINOIMPLEMENTATION_H
#define ARDUINOEXAMPLE_ARDUINOIMPLEMENTATION_H


class ArduinoImplementation {

};


#endif //ARDUINOEXAMPLE_ARDUINOIMPLEMENTATION_H
